name: Protocol Build & Push Image to AWS ECR - Dev2

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - jakob-dydx/build-and-push-dev2

jobs:
  build-and-push-dev2:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./protocol
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: '0'  # without this, ignite fails.

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_VALIDATOR_DEV2 }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_VALIDATOR_DEV2 }}
            aws-region: us-east-2

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, Tag, and Push the Image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: dev2-validator
          run: |
            make localnet-build-amd64
            commit_hash=$(git rev-parse --short=7 HEAD)
            docker build \
              --platform amd64 \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:$commit_hash \
              -f testing/testnet-dev/Dockerfile .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags